import type { Metadata } from "next";
import "./globals.css";
import { Walter_Turncoat, Poppins } from 'next/font/google';

const poppins = Poppins({ weight: "400", subsets: ['latin'] });
const walterTurncoat = Walter_Turncoat({ weight: "400", subsets: ['latin'] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${walterTurncoat.className} min-w-screen overflow-x-hidden`}>{children}</body>
    </html>
  );
}
